### PR TITLE
Update from syseng 

### PR DESCRIPTION
**Pull request by rhiannonlynne**
The syseng_throughputs repo now contains the 'authoritative' components for the throughputs.
This is an update of the files, using the data from that repo. The syseng_throughputs repo version is encoded in the file headers.

### CODE REVIEW

**Comment by rhiannonlynne** [comment]
@danielsf  I would like you to be aware of this update and to see if any of the changes impact catalogs in some way I didn't expect (maybe in the components list?), but I guess @connolly is the one to sign off on making the upgrade on the package.

**Comment by connolly** [comment]
Comments:
- The top level README.md should describe what the repository contains (e.g. the component files that define the overall throughput for the LSST system including atmosphere, reflective and transmissive surfaces) and explain the layout of the directory structure (the README.md(s) in the subdirectories are much clearer)
- do the filter responses include expected leaks?
- as the filters evolve (or our knowledge of the filters evolves) do we just overwrite the throughputs and rely on tags and releases to track the changes? How do we capture what changes between releases (in words). I think we should have a release file that describes the changes in assumptions or measurements from one release to the next.
- in the baseline filters directory the files filter_g.dat etc have $LastChangedRevision$ and  $Id$ as empty
- the assumptions for the m1m3 surfaces (eg protected/aged/bare aluminium) should be noted in the README (or release notes) as we provide all three surfaces and just linking m1.dat to the one we are using will not be picked up by most users. Is m1_ProtAl_Ideal.dat the current choice as I thought we were using bare Al
- Did you validate that the imsim (should now be phosim) filters are what is currently being used in phosim

**Comment by rhiannonlynne** [comment]
READMEs: 
I will update the top-level readme to be simpler. 

In the particular readme for the baseline throughputs -- I actually don't think I want to put too much information here, as opposed to the information being in the syseng_throughputs repo, as I think that is where it really ought to be -- the syseng team should be the ones updating things like whether we're using the bare or protected aluminum or an AlAg hybrid, and what the assumptions are for the coatings, etc. Otherwise, we have to update it and document it in two places. That's why I wanted to make sure that the syseng_throughputs repo was referenced and version tagged -- and then the information on the specifics should be there. Thoughts?

**Comment by rhiannonlynne** [comment]
Filters + leaks -- these are the filters as we get them from Chuck. I do not believe that these versions include any expected leaks, as they are just the requirements given to the vendors, rather than something like what Kirk did where he made a specific implementation of the filter throughputs. 
If you want to include leaks, we'd have to put in something like the expected performance throughputs, rather than the requirements -- but Chuck wants to use the requirements at this time.

**Comment by rhiannonlynne** [comment]
Comment -- "as the filters evolve (or our knowledge of the filters evolves) do we just overwrite the throughputs and rely on tags and releases to track the changes? How do we capture what changes between releases (in words). I think we should have a release file that describes the changes in assumptions or measurements from one release to the next."
Yes .. but I think this should go in the syseng_throughputs repo, and be maintained by the syseng team.

**Comment by rhiannonlynne** [comment]
The $Id$ etc -- these actually shouldn't be there. They are an old thing from when we used SVN. They actually _aren't_ there in the new branch versions (but are in master). Are you sure you checked the right version of the files? :)

**Comment by rhiannonlynne** [comment]
Imsim files - I didn't know how to validate the imsim files. Should I just drop these versions? Apparently there is a script in phosim that should be possible to use, but I'm not sure if it's updated etc.

**Comment by rhiannonlynne** [comment]
In general -- I now view the 'baseline curves' in this repo as a derived product from syseng_throughputs, and we add other throughput curves to make life easier (e.g. the Megacam and SDSS curves). To avoid duplication of documentation, I'd prefer the documentation on what changes to live in the syseng_throughputs repo, with a pointer here to the documentation there. (note  - there is actually not really any documentation there at present. We should talk to Chuck how he wants to update that .. I'd prefer the update notes be in the actual files, as that way it should be easier to make sure that the documentation be updated). 

syseng_throughputs components : https://github.com/lsst-pst/syseng_throughputs/tree/master/components

**Comment by connolly** [comment]
Comments from our discussion
- there should be a pointer to any readme in the syseng repo  (so a user knows what has changed). The syseng readme should be updated with what has changed for each release
- a user will likely only see this repo and not the syseng version so that we will need the definitions of what is baseline here 
- add an entry in the files that has wavelength_start, wavelength_end for the definition of the useful spectral range (ie how the filter can be truncated). When we have leaks included then a user might get confused and truncate a filter at the first zero they encounter.

Other than that looks good to merge

**Comment by rhiannonlynne** [comment]
@connolly 
I updated the readme in the syseng_throughputs repo, am waiting on Chuck to validate. 
I copied the version of that readme here and added wavelen_blue/red to each relevant file. 
I'll update these curves once I retag the syseng repo, so that the version number becomes 1.1.

**Pull request merged**
